//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaidEasy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract
    {
        public int Id { get; set; }
        public int WorkerId { get; set; }
        public string WorkerName { get; set; }
        public int UserId { get; set; }
        public string StartMonth { get; set; }
        public string EndMonth { get; set; }
        public string startTime { get; set; }
        public string endTime { get; set; }
        public int Amount { get; set; }
        public string Worklist { get; set; }
        public string status { get; set; }
    
        public virtual worker worker { get; set; }
        public virtual user user { get; set; }
    }
}
