//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaidEasy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoEntities : DbContext
    {
        public DemoEntities()
            : base("name=DemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<contactu> contactus { get; set; }
        public virtual DbSet<contract> contracts { get; set; }
        public virtual DbSet<thana> thanas { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<work> works { get; set; }
        public virtual DbSet<worker> workers { get; set; }
        public virtual DbSet<workerreview> workerreviews { get; set; }
    }
}
