//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaidEasy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.contracts = new HashSet<contract>();
        }
    
        public int UserId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string type { get; set; }
        public string Name { get; set; }
        public string mobile { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string image { get; set; }
        public string thana { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contract> contracts { get; set; }
    }
}
