//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaidEasy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public worker()
        {
            this.contracts = new HashSet<contract>();
            this.workerreviews = new HashSet<workerreview>();
        }
    
        public int WorkerId { get; set; }
        public string Name { get; set; }
        public string fatherName { get; set; }
        public string mobile { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string Area { get; set; }
        public string type { get; set; }
        public int experience { get; set; }
        public string joinDate { get; set; }
        public string updateStatus { get; set; }
        public Nullable<double> rating { get; set; }
        public string image { get; set; }
        public string status { get; set; }
        public string gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contract> contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<workerreview> workerreviews { get; set; }
    }
}
